### ISSUE TITLE
OpenID integration might stop working after upgrading to our v0.4.0

### ISSUE THREAD

**Issue by webwurst** [giantswarm/efk-stack-app#52]
Our app version `0.4.0` corresponds to OpenDistro `1.12.0` and Kibana `7.10.0`.

The previous release was missing the feature to hand out refresh tokens for the OpenID authentication, so users were automatically logged out after some time. This feature is now available and enabled by default, but seems to lead to a too large cookie size in some cases, which in result breaks the authentication flow completely.

As a temporary workaround merge this to your chart config `values.yaml`:

```yaml
opendistro-es:
  kibana:
    config:
      opendistro_security.openid.refresh_tokens: false
```
Upstream issue for reference: https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/issues/516

Thanks to @wind0r for reporting :) Can you please check once for correctness?
